name: 电信签到 (China Telecom Check-in)

on:
  workflow_dispatch:
  schedule:
    # 每天早上 8:00 UTC (北京时间下午 4:00) 运行，您可以根据需要调整时间
    - cron: '0 0 * * *'

jobs:
  run_checkin:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 推荐使用一个稳定的LTS版本

      - name: Install dependencies
        run: npm install

      - name: Run China Telecom Check-in Script
        # 脚本通过环境变量读取账号信息
        run: npm start
        env:
          # 请注意，脚本中的环境变量名称是混淆的，通常这类脚本会读取一个包含所有账号的变量。
          # 假设脚本读取名为 'CT_ACCOUNTS' 的环境变量。
          # 您可能需要根据原脚本的实际要求来调整此变量名。
          CT_ACCOUNTS: ${{ secrets.CT_ACCOUNTS }}
